author:
  name   : "Ziwei Wang"
  avatar : "/images/CV1.jpeg"
  bio    : "Ph.D. candidate at HUST working on BCI and smart healthcare."
  location : "Wuhan, China"
  employer : "Huazhong University of Science and Technology"
  email  : "vivi@hust.edu.cn"

  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:vivi@hust.edu.cn"

    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=fjlXqvQAAAAJ&hl=en"

    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wzwvv"

    - label: "CV"
      icon: "fas fa-fw fa-file-alt"
      url: "/files/CV_Ziwei_Wang.pdf"
